# Model strings (matching Java RuleGen_en.properties)
CAT = "cat"
FEATURE_X = "FeatureX"
MATCH_X = "MatchX"
PHRASE = "phrase"
PREFIX = "prefix"
SRC = "src"
SUFFIX = "suffix"
TGT = "tgt"
WORD = "word"
HEAD = "head"
NAME_MISSING = "This rule needs a name"
RULE_DUPLICATED = " - Copy"
UNMARKED = "unmarked"
